name: Build and Commit to Main

on:
  push:
    branches:
      - main

jobs:
  build-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0 # Ensure the full history is fetched for committing changes

    - name: Install dependencies
      run: npm install # Add this step if your project uses npm

    - name: Build project
      run: npm run build # Replace with your build command if applicable

    - name: Move build output to root
      run: |
        mv public/* . # Move build output to the root directory
        rm -rf public/

    - name: Replace GitHub Client ID
      run: sed -i 's/__GITHUB_CLIENT_ID__/${{ secrets.Client_ID }}/g' index.html # Adjust the file path if necessary

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add .
        git commit -m "Update built files"
        git push origin main
